<a href="https://colab.research.google.com/github/sanaahmad4222/python/blob/main/NumpyAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Array:", arr)
print("Type:", type(arr))


Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


In [ ]:
import numpy as np

arr = np.arange(10, 51)

print("Array:", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)



Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Shape: (41,)
Size: 41


In [ ]:
import numpy as np

arr = np.zeros((3, 4))
print("Original Array:\n", arr)

arr[:] = 5
print("Updated Array:\n", arr)


Original Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Updated Array:
 [[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [ ]:
import numpy as np

arr = np.random.randint(1, 101, size=15)
print("Array:", arr)

print("Maximum:", arr.max())
print("Minimum:", arr.min())
print("Mean:", arr.mean())


Array: [28 71 52 64 32 96 64  5  1 61 87  8 51 23 44]
Maximum: 96
Minimum: 1
Mean: 45.8


In [ ]:
import numpy as np

arr = np.arange(1, 21)
print("Original Array:", arr)

even_nums = arr[arr % 2 == 0]
print("Even Numbers:", even_nums)

reversed_arr = arr[::-1]
print("Reversed Array:", reversed_arr)


Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Even Numbers: [ 2  4  6  8 10 12 14 16 18 20]
Reversed Array: [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)

print("First Element:", arr[0])
print("Last Element:", arr[-1])


Array: [10 20 30 40 50]
First Element: 10
Last Element: 50


In [ ]:
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)
print("Original Array:\n", arr)

sub_arr = arr[:2, -2:]
print("First two rows & last two columns:\n", sub_arr)

np.fill_diagonal(arr, 0)
print("Array with diagonal replaced by 0:\n", arr)


Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First two rows & last two columns:
 [[3 4]
 [7 8]]
Array with diagonal replaced by 0:
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [ ]:
import numpy as np

arr = np.random.randint(1, 101, size=25)
print("Original Array:\n", arr)

sorted_arr = np.sort(arr)
print("Sorted Array:\n", sorted_arr)


Original Array:
 [ 60  14  77  18  89  47  48  91  93  73  43  35  49  87  95  15  27  80
  12  30  58 100  17  96  47]
Sorted Array:
 [ 12  14  15  17  18  27  30  35  43  47  47  48  49  58  60  73  77  80
  87  89  91  93  95  96 100]


In [ ]:
import numpy as np

arr = np.arange(1, 11)
print("Array:", arr)

print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Sum:", np.sum(arr))


Array: [ 1  2  3  4  5  6  7  8  9 10]
Maximum: 10
Minimum: 1
Sum: 55


In [ ]:
import numpy as np

arr = np.arange(1, 37)
arr_2d = arr.reshape(6, 6)

print("2D Array (6x6):\n", arr_2d)

row_sum = np.sum(arr_2d, axis=1)
print("Sum of each row:", row_sum)

col_sum = np.sum(arr_2d, axis=0)
print("Sum of each column:", col_sum)


2D Array (6x6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sum of each row: [ 21  57  93 129 165 201]
Sum of each column: [ 96 102 108 114 120 126]
